"use client";

import ArrowBackIosNewRoundedIcon from "@mui/icons-material/ArrowBackIosNewRounded";
import ArrowForwardIosRoundedIcon from "@mui/icons-material/ArrowForwardIosRounded";
import ArrowForwardRoundedIcon from "@mui/icons-material/ArrowForwardRounded";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import CategoryRoundedIcon from "@mui/icons-material/CategoryRounded";
import CoffeeRoundedIcon from "@mui/icons-material/CoffeeRounded";
import FavoriteRoundedIcon from "@mui/icons-material/FavoriteRounded";
import Inventory2RoundedIcon from "@mui/icons-material/Inventory2Rounded";
import LocalMallRoundedIcon from "@mui/icons-material/LocalMallRounded";
import MedicationRoundedIcon from "@mui/icons-material/MedicationRounded";
import SmartphoneRoundedIcon from "@mui/icons-material/SmartphoneRounded";
import WatchRoundedIcon from "@mui/icons-material/WatchRounded";
import LocalShippingOutlinedIcon from "@mui/icons-material/LocalShippingOutlined";
import PaymentOutlinedIcon from "@mui/icons-material/PaymentOutlined";
import VerifiedOutlinedIcon from "@mui/icons-material/VerifiedOutlined";
import { Box, Button, Chip, Container, IconButton, Paper, Stack, Typography } from "@mui/material";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { products, type StoreProduct } from "./TwcStoreProvider";
import TwcProductCard from "./TwcProductCard";

export default function TwcHomeView({ onAdd }: { onAdd: (product: StoreProduct) => void }) {
  const router = useRouter();
  const categories = [...new Set(products.map((product) => product.category))].slice(0, 8);
  return <Box sx={{ bgcolor: "background.default" }}><Hero router={router} /><Container maxWidth="xl"><TrustStrip /><CategoryCarousel categories={categories} onSelect={(category) => router.push(`/twc-ecommerce/shop?category=${encodeURIComponent(category)}`)} onViewAll={() => router.push("/twc-ecommerce/shop")} /><HomeProductSection id="featured-products" eyebrow="CUSTOMER FAVORITES" title="Trending right now" products={products.slice(0, 4)} onAdd={onAdd} onViewAll={() => router.push("/twc-ecommerce/shop")} /></Container><Box sx={{ bgcolor: "action.hover", my: { xs: 5, md: 8 } }}><Container maxWidth="xl"><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, minHeight: { md: 390 } }}><Box component="img" src="/images/twc/middle-banner.webp" alt="Everyday accessories and essentials" sx={{ height: { xs: 250, md: "100%" }, objectFit: "cover", width: "100%" }} /><Box sx={{ alignSelf: "center", p: { xs: 3, md: 7 } }}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>MADE FOR REAL ROUTINES</Typography><Typography component="h2" sx={{ fontSize: { xs: 30, md: 42 }, fontWeight: 900, letterSpacing: "-.06em", lineHeight: 1.05, mt: 1 }}>Small upgrades can make every day feel better.</Typography><Typography color="text.secondary" sx={{ lineHeight: 1.7, mt: 1.5 }}>Discover practical products chosen for busy Filipino families, professionals, and anyone building a more intentional routine.</Typography><Button onClick={() => router.push("/twc-ecommerce/shop")} sx={{ mt: 2 }} variant="contained">Discover the collection</Button></Box></Box></Container></Box><Container maxWidth="xl"><HomeProductSection eyebrow="JUST IN" title="New arrivals" products={products.slice(4, 8)} onAdd={onAdd} onViewAll={() => router.push("/twc-ecommerce/shop")} /><Paper sx={{ alignItems: { xs: "flex-start", sm: "center" }, bgcolor: "#162433", color: "#fff", display: "flex", flexDirection: { xs: "column", sm: "row" }, justifyContent: "space-between", gap: 2, mb: { xs: 5, md: 8 }, mt: { xs: 6, md: 8 }, p: { xs: 3, md: 4 } }}><Box><Typography sx={{ color: "#8bc79f", fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>READY WHEN YOU ARE</Typography><Typography component="h2" sx={{ fontSize: { xs: 24, md: 30 }, fontWeight: 900, mt: .75 }}>Find something good for your routine.</Typography></Box><Button onClick={() => router.push("/twc-ecommerce/shop")} endIcon={<ArrowForwardRoundedIcon />} sx={{ bgcolor: "#fff", color: "#162433", flexShrink: 0, "&:hover": { bgcolor: "#e8f0e4" } }}>Start shopping</Button></Paper></Container></Box>;
}

function Hero({ router }: { router: ReturnType<typeof useRouter> }) { return <Box sx={{ bgcolor: "#e8f0e4", overflow: "hidden" }}><Container maxWidth="xl"><Box sx={{ display: "grid", gap: { xs: 3, md: 6 }, gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, minHeight: { md: 570 }, py: { xs: 5, md: 8 } }}><Box sx={{ alignSelf: "center", maxWidth: 620 }}><Chip label="TWC ONLINE STORE · OFFLINE DEMO" sx={{ bgcolor: "rgba(47,125,50,.12)", color: "primary.main", fontSize: 11, fontWeight: 900, letterSpacing: ".08em" }} /><Typography component="h1" sx={{ color: "#16331e", fontSize: { xs: 46, sm: 62, md: 76 }, fontWeight: 900, letterSpacing: "-.08em", lineHeight: .94, mt: 2 }}>Better choices for<br />your everyday life.</Typography><Typography sx={{ color: "#496653", fontSize: { xs: 15, md: 18 }, lineHeight: 1.7, maxWidth: 540, mt: 2 }}>Shop trusted wellness products, useful essentials, and personal style finds—all in one place.</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ mt: 3.5 }}><Button onClick={() => router.push("/twc-ecommerce/shop")} endIcon={<ArrowForwardRoundedIcon />} size="large" variant="contained">Shop the collection</Button><Button onClick={() => document.getElementById("featured-products")?.scrollIntoView({ behavior: "smooth" })} size="large" sx={{ color: "#16331e" }}>Explore best sellers</Button></Stack><Stack direction="row" spacing={3} sx={{ mt: 4 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><VerifiedOutlinedIcon sx={{ color: "primary.main", fontSize: 20 }} /><Typography sx={{ color: "#496653", fontSize: 12, fontWeight: 700 }}>Carefully selected</Typography></Stack><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><LocalShippingOutlinedIcon sx={{ color: "primary.main", fontSize: 20 }} /><Typography sx={{ color: "#496653", fontSize: 12, fontWeight: 700 }}>Delivered nationwide</Typography></Stack></Stack></Box><Box sx={{ alignItems: "center", display: "flex", justifyContent: "center", minHeight: { xs: 300, md: 500 }, position: "relative" }}><Box sx={{ bgcolor: "#c8dfc8", borderRadius: "50%", height: { xs: 280, md: 450 }, position: "absolute", width: { xs: 280, md: 450 } }} /><Box component="img" src="/images/twc/hero-banner.jpg" alt="TWC lifestyle collection" sx={{ borderRadius: 4, boxShadow: "0 28px 34px rgba(27,62,42,.22)", height: { xs: 270, md: 370 }, maxWidth: "94%", objectFit: "cover", position: "relative", transform: "rotate(-3deg)", width: { xs: "94%", md: 520 }, zIndex: 1 }} /><Paper elevation={3} sx={{ bottom: { xs: 12, md: 38 }, left: { xs: 4, md: 12 }, p: 2, position: "absolute", zIndex: 2 }}><Typography color="text.secondary" sx={{ fontSize: 11 }}>A considered everyday edit</Typography><Typography sx={{ fontSize: 14, fontWeight: 900 }}>Style, wellness, and useful things.</Typography></Paper></Box></Box></Container></Box>; }

function TrustStrip() { return <Box sx={{ display: "grid", gap: 1.5, gridTemplateColumns: { xs: "1fr", sm: "repeat(3, 1fr)" }, py: 2 }}>{[[<AutoAwesomeRoundedIcon key="many" />, "One store, many needs", "Wellness, beauty, bags, watches, and more."], [<VerifiedOutlinedIcon key="confidence" />, "Shop with confidence", "Product details and support at every step."], [<PaymentOutlinedIcon key="checkout" />, "Simple checkout", "Keep your cart until you are ready."]].map(([icon, title, detail]) => <Paper key={String(title)} elevation={0} sx={{ alignItems: "center", bgcolor: "action.hover", display: "flex", gap: 1.5, p: 2 }}><Box sx={{ color: "primary.main", display: "flex" }}>{icon}</Box><Box><Typography sx={{ fontSize: 13, fontWeight: 800 }}>{title}</Typography><Typography color="text.secondary" sx={{ fontSize: 11, mt: .25 }}>{detail}</Typography></Box></Paper>)}</Box>; }

function CategoryIcon({ category }: { category: string }) { const key = category.toLowerCase(); if (key.includes("bundle")) return <Inventory2RoundedIcon fontSize="small" />; if (key.includes("skin") || key.includes("beauty")) return <FavoriteRoundedIcon fontSize="small" />; if (key.includes("intimate")) return <MedicationRoundedIcon fontSize="small" />; if (key.includes("beverage")) return <CoffeeRoundedIcon fontSize="small" />; if (key.includes("nutraceutical") || key.includes("health")) return <MedicationRoundedIcon fontSize="small" />; if (key.includes("bag")) return <LocalMallRoundedIcon fontSize="small" />; if (key.includes("electronic")) return <SmartphoneRoundedIcon fontSize="small" />; if (key.includes("watch")) return <WatchRoundedIcon fontSize="small" />; return <CategoryRoundedIcon fontSize="small" />; }

function CategoryCarousel({ categories, onSelect, onViewAll }: { categories: string[]; onSelect: (category: string) => void; onViewAll: () => void }) { const viewport = useRef<HTMLDivElement>(null); const [canPrev, setCanPrev] = useState(false); const [canNext, setCanNext] = useState(true); const update = () => { const node = viewport.current; if (!node) return; setCanPrev(node.scrollLeft > 4); setCanNext(node.scrollLeft < node.scrollWidth - node.clientWidth - 4); }; useEffect(() => { update(); const node = viewport.current; node?.addEventListener("scroll", update, { passive: true }); window.addEventListener("resize", update); return () => { node?.removeEventListener("scroll", update); window.removeEventListener("resize", update); }; }, []); const move = (direction: number) => viewport.current?.scrollBy({ left: direction * (viewport.current.clientWidth * .72), behavior: "smooth" }); return <Box sx={{ py: { xs: 5, md: 8 } }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ alignItems: { sm: "end" }, justifyContent: "space-between", mb: 3, gap: 2 }}><Box><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>FIND YOUR FIT</Typography><Typography component="h2" sx={{ fontSize: { xs: 30, md: 42 }, fontWeight: 900, letterSpacing: "-.06em", mt: .5 }}>Shop by category</Typography></Box><Button onClick={onViewAll} endIcon={<ArrowForwardRoundedIcon />}>View all products</Button></Stack><Stack direction="row" spacing={1.5} sx={{ alignItems: "center" }}><IconButton disabled={!canPrev} onClick={() => move(-1)} aria-label="Previous categories" sx={{ border: 1, borderColor: "divider", flexShrink: 0 }}><ArrowBackIosNewRoundedIcon sx={{ fontSize: 16 }} /></IconButton><Box ref={viewport} sx={{ display: "flex", flex: 1, gap: 1.5, minWidth: 0, overflowX: "auto", scrollSnapType: "x mandatory", scrollbarWidth: "none", "&::-webkit-scrollbar": { display: "none" } }}>{categories.map((category) => <Button key={category} onClick={() => onSelect(category)} sx={{ alignItems: "center", border: 1, borderColor: "divider", color: "text.primary", display: "flex", flex: { xs: "0 0 calc(50% - 6px)", sm: "0 0 calc(33.333% - 8px)", md: "0 0 calc(16.666% - 13px)" }, flexDirection: "column", gap: .75, minHeight: 112, justifyContent: "center", scrollSnapAlign: "start", px: 1, textAlign: "center" }}><Box sx={{ bgcolor: "action.hover", borderRadius: "50%", color: "primary.main", display: "grid", height: 40, placeItems: "center", width: 40 }}><CategoryIcon category={category} /></Box><Typography sx={{ fontSize: 12, fontWeight: 800 }}>{category}</Typography><Typography color="text.secondary" sx={{ fontSize: 10 }}>{products.filter((product) => product.category === category).length} products</Typography></Button>)}</Box><IconButton disabled={!canNext} onClick={() => move(1)} aria-label="Next categories" sx={{ border: 1, borderColor: "divider", flexShrink: 0 }}><ArrowForwardIosRoundedIcon sx={{ fontSize: 16 }} /></IconButton></Stack></Box>; }

function HomeProductSection({ id, eyebrow, title, products: sectionProducts, onAdd, onViewAll }: { id?: string; eyebrow: string; title: string; products: StoreProduct[]; onAdd: (product: StoreProduct) => void; onViewAll: () => void }) { return <Box id={id} sx={{ pb: { xs: 5, md: 8 } }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ alignItems: { sm: "end" }, justifyContent: "space-between", mb: 3, gap: 2 }}><Box><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>{eyebrow}</Typography><Typography component="h2" sx={{ fontSize: { xs: 30, md: 42 }, fontWeight: 900, letterSpacing: "-.06em", mt: .5 }}>{title}</Typography></Box><Button onClick={onViewAll} endIcon={<ArrowForwardRoundedIcon />}>Shop all</Button></Stack><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: { xs: "repeat(2, minmax(0, 1fr))", md: "repeat(4, minmax(0, 1fr))" } }}>{sectionProducts.map((product) => <TwcProductCard key={product.slug} product={product} onAdd={() => onAdd(product)} />)}</Box></Box>; }
