"use client";

import ArrowForwardRoundedIcon from "@mui/icons-material/ArrowForwardRounded";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import LocalShippingOutlinedIcon from "@mui/icons-material/LocalShippingOutlined";
import PaymentOutlinedIcon from "@mui/icons-material/PaymentOutlined";
import VerifiedOutlinedIcon from "@mui/icons-material/VerifiedOutlined";
import { Box, Button, Chip, Container, Divider, Paper, Stack, Typography } from "@mui/material";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { products, type StoreProduct } from "./TwcStoreProvider";
import TwcProductCard from "./TwcProductCard";
import WellnessOrganicHome from "./WellnessOrganicHome";
import ModernMarketplaceHome from "./ModernMarketplaceHome";
import CorporateCommerceHome from "./CorporateCommerceHome";
import { useStorefrontTheme } from "./twcEcommerceTheme";
import { premiumMedia, selectPremiumProducts } from "./storefrontContent";
import { StorefrontCarousel } from "./StorefrontPrimitives";

export default function TwcHomeView({ onAdd }: { onAdd: (product: StoreProduct) => void }) {
  const { themeName } = useStorefrontTheme();
  const router = useRouter();
  useEffect(() => {
    const section = new URLSearchParams(window.location.search).get("section");
    if (!section || !["collections", "journal", "about", "story", "benefits", "faq"].includes(section)) return;
    const frame = window.requestAnimationFrame(() => document.getElementById(section)?.scrollIntoView({ behavior: "smooth", block: "start" }));
    window.history.replaceState(null, "", window.location.pathname);
    return () => window.cancelAnimationFrame(frame);
  }, []);
  const categories = [...new Set(products.map((product) => product.category))].slice(0, 8);
  const openShop = (category?: string) => router.push(category ? `/twc-ecommerce/shop?category=${encodeURIComponent(category)}` : "/twc-ecommerce/shop");

  if (themeName === "premium-beauty") return <PremiumBeautyHome categories={categories} onAdd={onAdd} onShop={openShop} />;
  if (themeName === "modern-marketplace") return <ModernMarketplaceHome categories={categories} onAdd={onAdd} onShop={openShop} />;
  if (themeName === "corporate-commerce") return <CorporateCommerceHome categories={categories} onAdd={onAdd} onShop={openShop} />;
  return <WellnessOrganicHome categories={categories} onAdd={onAdd} onShop={openShop} />;
}

function PremiumBeautyHome({ categories, onAdd, onShop }: HomeProps) {
  const { themeConfig } = useStorefrontTheme();
  const curatedProducts = selectPremiumProducts(products);
  return <>
    <PremiumHero onShop={() => onShop()} />
    <Box sx={{ bgcolor: "background.paper", py: { xs: 5, md: 8 } }}><Container maxWidth="lg"><Stack direction={{ xs: "column", sm: "row" }} sx={{ alignItems: { sm: "end" }, justifyContent: "space-between", mb: 3, gap: 2 }}><Box><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>THE NEW EDIT</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 34, md: 50 }, fontWeight: 500 }}>Featured collection</Typography></Box><Button onClick={() => onShop()} endIcon={<ArrowForwardRoundedIcon />}>View all products</Button></Stack><ProductRail products={curatedProducts.slice(0, 4)} onAdd={onAdd} /></Container></Box>
    <PremiumCategoryGrid categories={premiumMedia.categories} onSelect={onShop} />
    <Container maxWidth="lg"><PremiumEditorial id="journal" image={premiumMedia.editorial.image} title="The beauty of a considered routine." copy="A little less noise. A little more intention. Explore products selected for the small rituals that help a day feel like your own." onShop={() => onShop()} /><PremiumCampaign image={premiumMedia.editorial.campaign} onShop={() => onShop()} /><PremiumAbout /><Box sx={{ py: { xs: 6, md: 10 } }}><SectionHeader eyebrow="DISCOVER YOUR NEXT FAVORITE" title="A collection with room to browse" action={<Button onClick={() => onShop()}>Shop the full edit</Button>} /><Box sx={{ display: "grid", gap: { xs: 2, md: 3 }, gridTemplateColumns: { xs: "repeat(2, 1fr)", sm: "repeat(3, 1fr)", md: "repeat(4, 1fr)" } }}>{curatedProducts.slice(4, 8).map((product) => <TwcProductCard key={product.slug} product={product} onAdd={() => onAdd(product)} />)}</Box></Box></Container>
    <Box sx={{ bgcolor: themeConfig.heroText, color: "#fff", px: 2, py: { xs: 7, md: 11 } }}><Container maxWidth="md" sx={{ textAlign: "center" }}><Typography sx={{ color: themeConfig.accent, fontSize: 11, fontWeight: 900, letterSpacing: ".15em" }}>A NOTE FROM TWC</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 34, md: 56 }, fontWeight: 500, lineHeight: 1.04, mt: 1 }}>Good things are worth taking your time with.</Typography><Typography sx={{ color: "rgba(255,255,255,.72)", lineHeight: 1.8, mt: 2, mx: "auto", maxWidth: 580 }}>A portfolio storefront study inspired by the calm confidence of modern direct-to-consumer brands.</Typography><Button onClick={() => onShop()} sx={{ bgcolor: "#fff", color: themeConfig.heroText, mt: 3 }}>Start exploring</Button></Container></Box>
    <Container maxWidth="md"><PremiumNewsletter /></Container>
  </>;
}

function PremiumHero({ onShop }: { onShop: () => void }) {
  return <StorefrontCarousel interval={7000} label="Premium Beauty editorial hero">{premiumMedia.heroes.map((slide) => <Box key={slide.title} sx={{ minHeight: { xs: 620, md: 720 }, position: "relative" }}><Box component="img" src={slide.image} alt="" sx={{ height: "100%", inset: 0, objectFit: "cover", position: "absolute", width: "100%" }} /><Box sx={{ bgcolor: "rgba(35,18,24,.28)", inset: 0, position: "absolute" }} /><Container maxWidth="lg" sx={{ height: "100%", position: "relative" }}><Stack sx={{ color: "#fff", justifyContent: "center", maxWidth: 580, minHeight: { xs: 620, md: 720 }, pb: 6, px: { xs: 2, md: 0 } }} spacing={2}><Typography sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".18em" }}>{slide.eyebrow}</Typography><Typography component="h1" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 52, md: 84 }, fontWeight: 500, letterSpacing: "-.04em", lineHeight: .95 }}>{slide.title}</Typography><Typography sx={{ color: "rgba(255,255,255,.86)", fontSize: 16, lineHeight: 1.8, maxWidth: 470 }}>{slide.description}</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ pt: 1 }}><Button onClick={onShop} sx={{ alignSelf: "flex-start", bgcolor: "#fff", color: "#3f2631", px: 3 }}>Shop the edit</Button><Button onClick={onShop} sx={{ alignSelf: "flex-start", borderColor: "rgba(255,255,255,.6)", color: "#fff", px: 3 }} variant="outlined">Explore collections</Button></Stack></Stack></Container></Box>)}</StorefrontCarousel>;
}

function PremiumCategoryGrid({ categories, onSelect }: { categories: { label: string; query: string; image: string }[]; onSelect: (category: string) => void }) {
  return <Box id="collections" sx={{ bgcolor: "#f4e7e4", py: { xs: 6, md: 10 }, scrollMarginTop: 90 }}><Container maxWidth="lg"><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>SHOP BY CATEGORY</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 34, md: 50 }, fontWeight: 500, mt: .5 }}>Find your kind of beautiful.</Typography><Box sx={{ display: "grid", gap: { xs: 2, md: 3 }, gridTemplateColumns: { xs: "repeat(2, 1fr)", md: "repeat(4, 1fr)" }, mt: 4 }}>{categories.map((category) => <Button key={category.label} onClick={() => onSelect(category.query)} sx={{ display: "block", p: 0, textAlign: "left", textTransform: "none" }}><Box sx={{ overflow: "hidden", position: "relative" }}><Box component="img" src={category.image} alt={category.label} sx={{ display: "block", height: { xs: 190, md: 300 }, objectFit: "cover", transition: "transform .45s", width: "100%", "&:hover": { transform: "scale(1.04)" } }} /><Box sx={{ bgcolor: "rgba(40,20,28,.25)", inset: 0, position: "absolute" }} /></Box><Typography sx={{ color: "text.primary", fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 20, mt: 1 }}>{category.label}</Typography></Button>)}</Box></Container></Box>;
}

function PremiumEditorial({ id, image, title, copy, onShop }: { id?: string; image: string; title: string; copy: string; onShop: () => void }) {
  return <Box id={id} sx={{ display: "grid", gap: { xs: 3, md: 8 }, gridTemplateColumns: { xs: "1fr", md: "1.05fr .95fr" }, py: { xs: 7, md: 13 }, scrollMarginTop: 90 }}><Box component="img" src={image} alt="Premium beauty lifestyle" sx={{ height: { xs: 360, md: 620 }, objectFit: "cover", width: "100%" }} /><Stack sx={{ alignSelf: "center", maxWidth: 460 }} spacing={2}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>THE TWC POINT OF VIEW</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 38, md: 58 }, fontWeight: 500, lineHeight: 1.02 }}>{title}</Typography><Typography color="text.secondary" sx={{ lineHeight: 1.9 }}>{copy}</Typography><Button onClick={onShop} sx={{ alignSelf: "flex-start" }} variant="outlined">Read the edit</Button></Stack></Box>;
}

function PremiumAbout() {
  const values = [["Browse with intention", "A slower, more spacious product discovery experience for a portfolio storefront."], ["One engine underneath", "The presentation changes by template while cart, checkout, shipping, and order state stay shared."], ["Made for the edit", "Content, imagery, and hierarchy are composed as a complete storefront—not just a color theme."]];
  return <Box id="about" sx={{ borderTop: 1, borderColor: "divider", py: { xs: 6, md: 9 }, scrollMarginTop: 90 }}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>ABOUT THIS STOREFRONT</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 34, md: 48 }, fontWeight: 500, mt: .5 }}>A visual study in considered commerce.</Typography><Box sx={{ display: "grid", gap: { xs: 2, md: 3 }, gridTemplateColumns: { xs: "1fr", md: "repeat(3, 1fr)" }, mt: 4 }}>{values.map(([title, copy]) => <Box key={title} sx={{ bgcolor: "#f8efed", p: { xs: 2.5, md: 3.5 } }}><Typography sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: 23 }}>{title}</Typography><Typography color="text.secondary" sx={{ lineHeight: 1.8, mt: 1 }}>{copy}</Typography></Box>)}</Box></Box>;
}

function PremiumCampaign({ image, onShop }: { image: string; onShop: () => void }) {
  return <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: ".9fr 1.1fr" }, minHeight: { md: 510 }, mb: { xs: 6, md: 12 } }}><Stack sx={{ bgcolor: "#3f2631", color: "#fff", justifyContent: "center", p: { xs: 4, md: 7 } }} spacing={2}><Typography sx={{ color: "#ead9d7", fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>THE SEASONAL CAMPAIGN</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 36, md: 54 }, fontWeight: 500, lineHeight: 1.05 }}>A little luxury, every day.</Typography><Typography sx={{ color: "rgba(255,255,255,.7)", lineHeight: 1.8 }}>Build a personal edit of products that make ordinary moments feel considered.</Typography><Button onClick={onShop} sx={{ alignSelf: "flex-start", bgcolor: "#fff", color: "#3f2631" }}>Shop the campaign</Button></Stack><Box component="img" src={image} alt="Premium beauty campaign" sx={{ height: { xs: 330, md: "100%" }, objectFit: "cover", width: "100%" }} /></Box>;
}

function PremiumNewsletter() {
  return <Box sx={{ borderBottom: 1, borderColor: "divider", py: { xs: 7, md: 10 }, textAlign: "center" }}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".16em" }}>STAY IN THE KNOW</Typography><Typography component="h2" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 32, md: 46 }, fontWeight: 500, mt: .5 }}>A better kind of inbox.</Typography><Typography color="text.secondary" sx={{ lineHeight: 1.8, mt: 1, mx: "auto", maxWidth: 520 }}>Demo newsletter content for new collections, considered finds, and occasional notes from the TWC edit.</Typography><Button sx={{ mt: 2 }} variant="outlined">Join the list</Button></Box>;
}

function WellnessHome({ categories, onAdd, onShop }: HomeProps) {
  return <>
    <LifestyleHero onShop={onShop} />
    <Container maxWidth="xl"><TrustStrip /><Box id="collections" sx={{ scrollMarginTop: 90 }}><SectionHeader eyebrow="FIND YOUR FIT" title="Shop by wellness goal" /><CategoryTiles categories={categories} onSelect={onShop} /></Box><Box id="featured" sx={{ scrollMarginTop: 90 }}><SectionHeader eyebrow="CUSTOMER FAVORITES" title="Trending right now" action={<Button onClick={() => onShop()}>Shop all</Button>} /><ProductRail products={products.slice(0, 4)} onAdd={onAdd} /></Box><Box id="story" sx={{ scrollMarginTop: 90 }}><StoryBlock onShop={onShop} /></Box><Box id="benefits" sx={{ scrollMarginTop: 90 }}><BenefitBlock /></Box><Box id="faq" sx={{ scrollMarginTop: 90 }}><FaqBlock /></Box><CtaBlock onShop={onShop} /></Container>
  </>;
}

function MarketplaceHome({ categories, onAdd, onShop }: HomeProps) {
  return <>
    <Container maxWidth="xl" sx={{ pt: 2 }}><CategoryTiles categories={categories} onSelect={onShop} compact /></Container>
    <MarketplaceHero onShop={onShop} />
    <Container maxWidth="xl"><DealStrip onShop={onShop} /><SectionHeader eyebrow="MOST POPULAR" title="Best sellers" action={<Button onClick={() => onShop()}>See all</Button>} /><ProductRail products={products.slice(0, 8)} onAdd={onAdd} dense /><SectionHeader eyebrow="MORE TO DISCOVER" title="All the useful things" /><ProductRail products={products.slice(8, 12)} onAdd={onAdd} dense /><CtaBlock onShop={onShop} /></Container>
  </>;
}

function CorporateHome({ categories, onAdd, onShop }: HomeProps) {
  return <>
    <CorporateHero onShop={onShop} />
    <Container maxWidth="xl"><SectionHeader eyebrow="FEATURED COLLECTION" title="A sharper everyday assortment" action={<Button onClick={() => onShop()}>Explore products</Button>} /><ProductRail products={products.slice(0, 4)} onAdd={onAdd} /><SectionHeader eyebrow="COLLECTIONS" title="Built around the way you live" /><CategoryTiles categories={categories} onSelect={onShop} /><StoryBlock onShop={onShop} /><BenefitBlock /><CtaBlock onShop={onShop} /></Container>
  </>;
}

type HomeProps = { categories: string[]; onAdd: (product: StoreProduct) => void; onShop: (category?: string) => void };

function EditorialHero({ onShop }: { onShop: () => void }) { return <Box sx={{ bgcolor: "#f4e7e4" }}><Container maxWidth="lg"><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1.1fr .9fr" }, minHeight: { md: 620 } }}><Box component="img" src="/images/twc/hero-banner.jpg" alt="Editorial TWC collection" sx={{ height: { xs: 330, md: 620 }, objectFit: "cover", width: "100%" }} /><Stack sx={{ alignSelf: "center", p: { xs: 3, md: 7 } }} spacing={2}><Typography sx={{ color: "#8b4962", fontSize: 11, fontWeight: 900, letterSpacing: ".17em" }}>TWC / THE NEW EDIT</Typography><Typography component="h1" sx={{ color: "#3f2631", fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 48, md: 72 }, fontWeight: 500, lineHeight: .98 }}>Everyday, edited.</Typography><Typography sx={{ color: "#6d5059", lineHeight: 1.8 }}>A calmer way to browse useful products, personal style, and small upgrades for real routines.</Typography><Button onClick={() => onShop()} sx={{ alignSelf: "flex-start", bgcolor: "#8b4962", color: "#fff", px: 3 }}>Shop the collection</Button></Stack></Box></Container></Box>; }

function LifestyleHero({ onShop }: { onShop: () => void }) { return <Box sx={{ bgcolor: "#e4f0e4" }}><Container maxWidth="xl"><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, minHeight: { md: 510 } }}><Stack sx={{ alignSelf: "center", maxWidth: 590, p: { xs: 3, md: 7 } }} spacing={2}><Chip label="WELLNESS ORGANIC · OFFLINE DEMO" sx={{ alignSelf: "flex-start", bgcolor: "#dcebdc", color: "#347153", fontWeight: 900 }} /><Typography component="h1" sx={{ color: "#173b27", fontSize: { xs: 46, md: 70 }, fontWeight: 900, letterSpacing: "-.08em", lineHeight: .95 }}>Better choices for your everyday life.</Typography><Typography sx={{ color: "#496653", lineHeight: 1.8 }}>Trusted wellness products, useful essentials, and personal style finds—all in one place.</Typography><Button onClick={() => onShop()} sx={{ alignSelf: "flex-start" }} variant="contained">Shop the collection</Button></Stack><Box component="img" src="/images/twc/hero-banner.jpg" alt="Wellness lifestyle collection" sx={{ height: { xs: 300, md: "100%" }, minHeight: { md: 510 }, objectFit: "cover", width: "100%" }} /></Box></Container></Box>; }

function MarketplaceHero({ onShop }: { onShop: () => void }) { return <Box sx={{ bgcolor: "#e6efff", borderBottom: 1, borderColor: "#c8d9fb", py: { xs: 4, md: 7 } }}><Container maxWidth="xl"><Stack direction={{ xs: "column", md: "row" }} sx={{ alignItems: { md: "center" }, justifyContent: "space-between", gap: 3 }}><Box><Typography color="primary.main" sx={{ fontSize: 12, fontWeight: 900, letterSpacing: ".12em" }}>DEALS THAT MOVE FAST</Typography><Typography component="h1" sx={{ color: "#142c63", fontSize: { xs: 42, md: 64 }, fontWeight: 950, letterSpacing: "-.08em", lineHeight: .95, mt: 1 }}>Find more. Shop faster.</Typography><Typography sx={{ color: "#4c6390", mt: 1.5 }}>Browse the full TWC catalog with a faster, denser shopping experience.</Typography><Button onClick={() => onShop()} sx={{ mt: 2 }} variant="contained">Browse all products</Button></Box><Box component="img" src="/images/twc/hero-banner.jpg" alt="Marketplace product selection" sx={{ height: { xs: 220, md: 310 }, objectFit: "cover", width: { xs: "100%", md: 470 } }} /></Stack></Container></Box>; }

function CorporateHero({ onShop }: { onShop: () => void }) { return <Box sx={{ bgcolor: "#e8eef3", borderBottom: 1, borderColor: "#cfdae1" }}><Container maxWidth="xl"><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1.2fr .8fr" }, minHeight: { md: 510 } }}><Stack sx={{ alignSelf: "center", maxWidth: 650, p: { xs: 3, md: 6 } }} spacing={2}><Typography sx={{ color: "#173f5f", fontSize: 12, fontWeight: 900, letterSpacing: ".16em" }}>TWC COMMERCE PLATFORM</Typography><Typography component="h1" sx={{ color: "#173044", fontSize: { xs: 44, md: 70 }, fontWeight: 900, letterSpacing: "-.07em", lineHeight: .95 }}>Commerce, clearly considered.</Typography><Typography color="text.secondary" sx={{ maxWidth: 520, lineHeight: 1.8 }}>A structured storefront for products that earn their place in everyday life.</Typography><Button onClick={() => onShop()} sx={{ alignSelf: "flex-start" }} variant="contained">Explore products</Button></Stack><Box component="img" src="/images/twc/hero-banner.jpg" alt="Corporate TWC product collection" sx={{ height: { xs: 280, md: "100%" }, minHeight: { md: 510 }, objectFit: "cover", width: "100%" }} /></Box></Container></Box>; }

function SectionHeader({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <Stack direction={{ xs: "column", sm: "row" }} sx={{ alignItems: { sm: "end" }, justifyContent: "space-between", mb: 3, mt: { xs: 6, md: 9 }, gap: 2 }}><Box><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>{eyebrow}</Typography><Typography component="h2" sx={{ fontSize: { xs: 30, md: 44 }, fontWeight: 900, letterSpacing: "-.06em", mt: .5 }}>{title}</Typography></Box>{action}</Stack>; }

function ProductRail({ products: items, onAdd, dense = false }: { products: StoreProduct[]; onAdd: (product: StoreProduct) => void; dense?: boolean }) { return <Box sx={{ display: "grid", gap: dense ? { xs: 1.5, md: 2 } : { xs: 2, md: 3.5 }, gridTemplateColumns: { xs: "repeat(2, minmax(0, 1fr))", sm: "repeat(3, minmax(0, 1fr))", lg: `repeat(${dense ? 4 : Math.min(items.length, 4)}, minmax(0, 1fr))` } }}>{items.map((product) => <TwcProductCard key={product.slug} product={product} onAdd={() => onAdd(product)} />)}</Box>; }

function CategoryTiles({ categories, onSelect, compact = false }: { categories: string[]; onSelect: (category: string) => void; compact?: boolean }) { return <Box sx={{ display: "grid", gap: compact ? 1 : 1.5, gridTemplateColumns: { xs: "repeat(2, 1fr)", sm: compact ? "repeat(4, 1fr)" : "repeat(4, 1fr)", md: compact ? "repeat(8, 1fr)" : "repeat(4, 1fr)" }, mb: compact ? 2 : 0 }}>{categories.map((category) => <Button key={category} onClick={() => onSelect(category)} sx={{ border: 1, borderColor: "divider", color: "text.primary", minHeight: compact ? 54 : 96, px: 1, textTransform: "none" }}>{category}</Button>)}</Box>; }

function TrustStrip() { return <Box sx={{ display: "grid", gap: 1.5, gridTemplateColumns: { xs: "1fr", sm: "repeat(3, 1fr)" }, py: { xs: 3, md: 5 } }}>{[[<AutoAwesomeRoundedIcon key="one" />, "One store, many needs", "Wellness, beauty, and useful essentials."], [<VerifiedOutlinedIcon key="two" />, "Shop with confidence", "Product details and support at every step."], [<PaymentOutlinedIcon key="three" />, "Simple checkout", "Keep your basket until you are ready."]].map(([icon, title, detail]) => <Paper key={String(title)} elevation={0} sx={{ alignItems: "center", bgcolor: "action.hover", display: "flex", gap: 1.5, p: 2 }}>{icon}<Box><Typography sx={{ fontSize: 13, fontWeight: 800 }}>{title}</Typography><Typography color="text.secondary" sx={{ fontSize: 11, mt: .25 }}>{detail}</Typography></Box></Paper>)}</Box>; }

function StoryBlock({ onShop }: { onShop: () => void }) { return <Box sx={{ display: "grid", gap: { xs: 3, md: 6 }, gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, my: { xs: 7, md: 10 } }}><Box component="img" src="/images/twc/middle-banner.webp" alt="Everyday TWC collection" sx={{ height: { xs: 260, md: 390 }, objectFit: "cover", width: "100%" }} /><Stack sx={{ alignSelf: "center", maxWidth: 520 }} spacing={2}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>MADE FOR REAL ROUTINES</Typography><Typography component="h2" sx={{ fontSize: { xs: 30, md: 44 }, fontWeight: 900, letterSpacing: "-.06em" }}>Small upgrades can make every day feel better.</Typography><Typography color="text.secondary" sx={{ lineHeight: 1.8 }}>This portfolio storefront uses shared commerce data to demonstrate how one platform can support different ways of shopping and different visual identities.</Typography><Button onClick={() => onShop()} sx={{ alignSelf: "flex-start" }} variant="outlined">Discover the collection</Button></Stack></Box>; }

function BenefitBlock() { return <Box sx={{ bgcolor: "action.hover", display: "grid", gap: 2, gridTemplateColumns: { xs: "1fr", md: "repeat(3, 1fr)" }, my: { xs: 6, md: 9 }, p: { xs: 2, md: 4 } }}>{[[<VerifiedOutlinedIcon key="quality" />, "Considered selection", "Products are presented through a shared, reusable catalog."], [<LocalShippingOutlinedIcon key="delivery" />, "Clear journey", "Browse, compare, add to basket, and continue through checkout."], [<PaymentOutlinedIcon key="payment" />, "Offline by design", "The portfolio flow demonstrates UI behavior without real payment."]].map(([icon, title, detail]) => <Stack key={String(title)} direction="row" spacing={1.5}><Box sx={{ color: "primary.main" }}>{icon}</Box><Box><Typography sx={{ fontWeight: 800 }}>{title}</Typography><Typography color="text.secondary" sx={{ fontSize: 13, lineHeight: 1.6, mt: .4 }}>{detail}</Typography></Box></Stack>)}</Box>; }

function DealStrip({ onShop }: { onShop: () => void }) { return <Paper sx={{ alignItems: { xs: "flex-start", sm: "center" }, bgcolor: "primary.main", color: "primary.contrastText", display: "flex", flexDirection: { xs: "column", sm: "row" }, justifyContent: "space-between", gap: 2, my: { xs: 4, md: 6 }, p: { xs: 2, md: 3 } }}><Box><Typography sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".12em" }}>FEATURED NOW</Typography><Typography sx={{ fontSize: 22, fontWeight: 900, mt: .5 }}>Browse the latest TWC collection.</Typography></Box><Button onClick={() => onShop()} sx={{ bgcolor: "#fff", color: "primary.main" }}>Shop now</Button></Paper>; }

function TestimonialBlock() { return <Box sx={{ borderTop: 1, borderColor: "divider", py: { xs: 5, md: 8 }, textAlign: "center" }}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>A QUIETER WAY TO SHOP</Typography><Typography component="blockquote" sx={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: { xs: 26, md: 38 }, fontStyle: "italic", fontWeight: 500, lineHeight: 1.3, maxWidth: 720, mx: "auto", mt: 2 }}>“The same commerce engine can feel entirely different when the experience is thoughtfully composed.”</Typography></Box>; }

function FaqBlock() { return <Box sx={{ borderTop: 1, borderColor: "divider", my: { xs: 6, md: 9 }, pt: 4 }}><Typography color="primary.main" sx={{ fontSize: 11, fontWeight: 900, letterSpacing: ".14em" }}>COMMON QUESTIONS</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 2 }}>{["Is this a live store?", "Can the same products use different themes?", "Does checkout process a real payment?"] .map((question, index) => <Stack direction="row" key={question} sx={{ justifyContent: "space-between", py: 2 }}><Typography sx={{ fontWeight: 800 }}>{question}</Typography><Typography color="text.secondary">{["No. This is an offline portfolio demonstration.", "Yes. The theme changes presentation while commerce state remains shared.", "No. Checkout is simulated locally."][index]}</Typography></Stack>)}</Stack></Box>; }

function CtaBlock({ onShop }: { onShop: () => void }) { return <Box sx={{ bgcolor: "primary.main", color: "primary.contrastText", my: { xs: 6, md: 9 }, p: { xs: 3, md: 5 }, textAlign: "center" }}><Typography component="h2" sx={{ fontSize: { xs: 28, md: 40 }, fontWeight: 900 }}>Find something good for your routine.</Typography><Button onClick={() => onShop()} sx={{ bgcolor: "#fff", color: "primary.main", mt: 2 }}>Start shopping</Button></Box>; }
