export type StoreProduct = {
  slug: string;
  name: string;
  brand: string | null;
  price: number;
  category: string;
  shop: string;
  image: string;
  images: string[];
  description: string;
  details: string;
  sku: string;
  stock: number | null;
  unlimitedStock: boolean;
  category1: string;
  category2: string;
  imageSources?: Array<{
    url: string;
    source: "catalog" | "external" | "blob";
    altText: string | null;
    isPrimary: boolean;
    sortOrder: number;
  }>;
  barleyPoint: number;
  shippingQuantity: number;
  forVirtualWarehouse: boolean;
  status: "draft" | "active" | "out_of_stock" | "archived";
  currency: string;
  compareAtPrice: number | null;
  weightGrams: number | null;
  lengthCm: number | null;
  widthCm: number | null;
  heightCm: number | null;
  shippingProfile: string | null;
  minimumOrderQuantity: number;
  maximumOrderQuantity: number | null;
  isFeatured: boolean;
  sortOrder: number;
  seoTitle: string | null;
  seoDescription: string | null;
  sourceProductId: string | null;
  sourceSnapshotAt: string | null;
};
